name: "Matrix Test"

on: [push]

jobs:
  matrix-job:
    name: "Run a matrix job"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        value: [matrix-test-1, matrix-test-2]
    steps:
      - name: "Output something"
        if: ${{ matrix.value != 'matrix-test-1' }}
        run: |
          echo ${{ matrix.value }}
  post-matrix-job:
    name: "Post matrix job"
    runs-on: ubuntu-latest
    needs: matrix-job
    steps:
#      - name: "Verify matrix jobs succeeded"
#        if: ${{ needs.matrix-job.result != 'success' }}
#        run: |
#          echo "A matrix job failed/was skipped."
#          exit 1
      - name: "Output something if matrix succeeds"
        run: echo "Woohoo"