name: "Matrix Test"

on: [push]

jobs:
  matrix-job:
    name: "Run a matrix job"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        value: [matrix-test-1, matrix-test-2]

    steps:
      - name: "Output something"
        run: echo ${{ matrix.value }}